language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jsutterfield/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jsutterfield/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk # travis supports integration with certain providers, one of them is aws
  region: "us-west-2" # from the beanstalk url
  app: "docker-react" # name from the app in beanstalk
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-187763489703"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
